<?php
// $Id$
/**
 * @file
 * Adds a Twitter feed processor to the Feeds module.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_twitter_feeds_plugins() {
  
  $plugin_dir = drupal_get_path('module', 'feeds_twitter') . '/plugins';
  
  // Fetchers
  
  $info['FeedsTwitterSearchFetcher'] = array(
    'name' => 'Twitter search',
    'description' => 'Download tweets from Twitter based on search criteria.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher', // This is the key name, not the class name.
      'class' => 'FeedsTwitterSearchFetcher',
      'file' => 'FeedsTwitterSearchFetcher.inc',
      'path' => "$plugin_dir/fetchers",
    ),
  );
    
  // Parsers
  
  if (feeds_library_exists('simplepie.inc', 'simplepie')) {
    $info['FeedsTwitterAtomParser'] = array(
      'name' => 'Twitter Atom parser',
      'description' => 'Parse Twitter feeds in Atom format.',
      'help' => 'Use <a href="http://simplepie.org">SimplePie</a> to parse Twitter feeds.',
      'handler' => array(
        'parent' => 'FeedsSimplePieParser',
        'class' => 'FeedsTwitterAtomParser',
        'file' => 'FeedsTwitterAtomParser.inc',
        'path' => "$plugin_dir/parsers",
      ),
    );    
  }
  return $info;
}
